#!/bin/sh
# Generate a full multi-language SDK set for a public API and publish it as its own repo.
# Usage:  sh gallery/publish.sh <name> <spec-url> [github-owner]
# Requires: node 22+, the inox CLI (npm run build), gh (authenticated) for the push step.
set -eu
name="${1:?usage: publish.sh <name> <spec-url> [owner]}"
url="${2:?usage: publish.sh <name> <spec-url> [owner]}"
owner="${3:-}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
work="gallery/out/$name"
case "$url" in *.yaml|*.yml) ex="yaml";; *) ex="json";; esac
mkdir -p "$work"
curl -fsSL "$url" -o "$work/openapi.$ex"

cat > "$work/sdkgen.yml" <<EOF
sdkgen: 1
organization: { name: $name }
project: { name: $name, display_name: $name }
spec: { path: ./openapi.$ex }
targets:
  typescript: { package_name: "@$name/sdk" }
  python:     { package_name: ${name}_sdk }
  go:         { module_path: github.com/${owner:-inox}/$name-sdk-go }
  ruby:       { gem_name: $name }
  java:       { namespace: com.$name, maven_group: com.$name, maven_artifact: $name }
  csharp:     { namespace: $(printf '%s' "$name" | awk '{print toupper(substr($0,1,1)) substr($0,2)}') }
EOF

INOX="npx tsx $ROOT/src/cli.ts"
( cd "$work" && $INOX generate --out generated && $INOX products --out generated && $INOX verify --out generated || true )

echo "✓ Generated $name SDKs in $work/generated"
if [ -n "$owner" ] && command -v gh >/dev/null 2>&1; then
  repo="inox-$name-sdks"
  ( cd "$work/generated" && git init -q -b main && git add -A \
    && git commit -q -m "$name SDKs — generated by Inox" \
    && gh repo create "$owner/$repo" --public --source=. --remote=origin --push )
  echo "✓ Published https://github.com/$owner/$repo"
else
  echo "Set a github owner + authenticate gh to auto-publish, e.g.:  sh gallery/publish.sh $name $url <owner>"
fi
